version: '5.0'
working_directory: /var/lib/fuel_upgrade/
log_path: /var/log/fuel_upgrade.log
puppet_modules_dir: puppet_modules
images_extension: tar

docker:
  url: unix://var/run/docker.sock
  api_version: '1.10'
  http_timeout: 160
  stop_container_timeout: 300

image_prefix: fuel/
container_prefix: fuel_

supervisor:
  configs_prefix: /etc/supervisord.d/
  current_configs_prefix: /etc/supervisord.d/current
  endpoint: 'unix:///var/run/supervisor.sock'
  group_name: fuel
  restart_timeout: 150

endpoints:
  nailgun:
    port: 8000
    host: 127.0.0.1

images:
  - id: astute
  - id: cobbler
  - id: mcollective
  - id: nailgun
  - id: nginx
  - id: ostf
  - id: postgres
  - id: rabbitmq
  - id: rsync
  - id: rsyslog
  - id: busybox

containers:
  - id: nailgun
    from_image: nailgun
    post_build_command: "bash -c '. /opt/nailgun/bin/activate; manage.py migrate upgrade head'"
    port_bindings:
      8001: 8001
    ports:
      - 8001
    links:
      - id: postgresql
        alias: db
      - id: rabbimq
        alias: rabbimq

    '/opt/fuel_plugins/ostf/bin/ostf-server --host=127.0.0.1 --port=8777 --log_file=/var/log/ostf.log --dbpath postgresql+psycopg2://ostf:ostf@127.0.0.1:5432/ostf'

  - id: assassind
    from_image: nailgun
    command: 'assassind'
    port_bindings:
      8001: 8001
    ports:
      - 8001
    links:
      - id: postgresql
        alias: db

  - id: postgresql
    from_image: postgres
    port_bindings:
      5432:
        - '127.0.0.1'
        - 5432
    ports:
      - 5432
    volumes_from:
      - volume_db

  - id: volume_db
    from_image: busybox
    post_build_command: 'true'
    volumes:
      - /var/lib/pgsql
    binds:
      '/var/lib/pgsql': '/var/lib/pgsql'
