version: '5.1'
working_directory: /var/lib/fuel_upgrade/
log_path: /var/log/fuel_upgrade.log
puppet_modules_dir: puppet_modules

docker:
  url: unix://var/run/docker.sock
  api_version: '1.9'
  http_timeout: 10
  stop_container_timeout: 90

container_prefix: fuel/

endpoints:
  nailgun:
    port: 8000
    host: 127.0.0.1

containers:
  - id: nailgun
    port: 8001

  - id: postgresql
    port: 5432

  - id: data
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql:rw

post_build_actions:
  # Run data container
  - action: run_and_wait
    data:
      id: data
      command: 'true'

  # Run postgresql
  - action: run
    data:
      id: postgresql

  # Run migration
  - action: run_and_wait
    data:
      id: nailgun
      command: bash -c '. /opt/nailgun/bin/activate; manage.py migrate upgrade head'
