version: '5.1'
working_directory: /var/lib/fuel_upgrade/
log_path: /var/log/fuel_upgrade.log
puppet_modules_dir: puppet_modules
images_extension: tar.xz

docker:
  url: unix://var/run/docker.sock
  api_version: '1.10'
  http_timeout: 160
  stop_container_timeout: 300

image_prefix: fuel/
container_prefix: fuel_

supervisor:
  configs_prefix: /etc/supervisord.d/
  current_configs_prefix: /etc/supervisord.d/current
  endpoint: 'unix:///var/run/supervisor.sock'
  group_name: fuel
  restart_timeout: 300

endpoints:
  nailgun:
    port: 8000
    host: 127.0.0.1

# images:
#   - id: astute
#   - id: cobbler
#   - id: dump
#   - id: mcollectived
#   - id: nginx
#   - id: ostf
#   - id: postgres
#   - id: puppet
#   - id: rabbitmq
#   - id: repo
#   - id: rsync
#   - id: rsyslog
#   - id: nailgun
#   - id: storage-dump
#   - id: storage-puppet
#   - id: storage-repo

images:
  - id: nailgun
  - id: postgresql
  - id: data

containers:
  - id: nailgun
    from_image: nailgun
    post_build_command: "bash -c '. /opt/nailgun/bin/activate; manage.py migrate upgrade head'"
    port_bindings:
      8001: 8001
    ports:
      - 8001
    links:
      - id: postgresql
        alias: db

  - id: postgresql
    from_image: postgresql
    port_bindings:
      5432:
        - '127.0.0.1'
        - 5432
    ports:
      - 5432
    volumes_from:
      - data

  - id: data
    from_image: data
    post_build_command: 'true'
    volumes:
      - /var/lib/postgresql
    binds:
      '/var/lib/postgresql': '/var/lib/postgresql'
