#!/usr/bin/env python
# -*- coding: utf-8 -*-

#    Copyright 2014 Mirantis, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import json
import argparse

"""
`fuel-upgrade` script installed on master node.
It downloads and runs upgrade system where we have
upgrade logic.
"""


def is_update_available():
    pass


def check_update():
    if is_update_available():
        pass


def run_upgrade():
    pass


def main(agrs):
    if agrs.check:
        check_update(args.src_path)
    elif agrs.upgrade:
        run_upgrade(args.src_path, args.dst_path)


def parse_args():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)

    group.add_argument(
        '--check',
        help='check if update is available',
        action='store_true')

    group.add_argument(
        '--upgrade',
        help='run upgrade',
        action='store_true')

    parser.add_argument(
        '--src_path',
        help='updates path',
        required=True)

    parser.add_argument(
        '--dst_path',
        help='updates path',
        required=True)

    return parser.parse_args()


if __name__ == '__main__':
    main(parse_args())
